server:
  port: 8081

spring:
  application:
    name: kafkalab

  kafka:
    bootstrap-servers: localhost:9092

    # Producer 설정
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner

    # Consumer 설정
    consumer:
      group-id: kafkalab-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest  # earliest → latest 변경
      enable-auto-commit: false

    # Listener 설정
    listener:
      ack-mode: manual
